-- =============================================================================
-- BeanFlow Coffee - POS operational source system
-- 01_schema.sql : tables and columns (schema `pos`)
--
-- Normalized OLTP design (3NF). This is the system of record that store tills
-- and the loyalty app write to; it is NOT an analytics model.
--
-- Conventions
--   * Primary/foreign/unique/check constraints live in 02_constraints.sql.
--     Column nullability and defaults live here, with the column.
--   * Identity columns are GENERATED BY DEFAULT so the synthetic data
--     simulator may insert explicit ids during seeding/backfill.
--   * Money       : NUMERIC(12,2), PHP.
--   * Timestamps  : TIMESTAMPTZ (stored as UTC instants; no business-timezone
--                   logic here - that belongs to the analytics layer).
--   * updated_at  : only on mutable tables; maintained by 03_triggers.sql.
--     Static reference tables (regions, areas, product_categories) have none.
--
-- Rerunnable: CREATE ... IF NOT EXISTS; no data is dropped.
-- =============================================================================

CREATE SCHEMA IF NOT EXISTS pos;

-- -----------------------------------------------------------------------------
-- Store hierarchy: regions -> areas -> stores
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS pos.regions (
    region_id       SMALLINT GENERATED BY DEFAULT AS IDENTITY,
    region_name     VARCHAR(50)  NOT NULL
);
COMMENT ON TABLE pos.regions IS 'Static reference: sales regions (e.g. NCR, North Luzon). One row per region.';

CREATE TABLE IF NOT EXISTS pos.areas (
    area_id         SMALLINT GENERATED BY DEFAULT AS IDENTITY,
    region_id       SMALLINT     NOT NULL,
    area_name       VARCHAR(80)  NOT NULL
);
COMMENT ON TABLE pos.areas IS 'Static reference: operating areas within a region. One row per area.';

CREATE TABLE IF NOT EXISTS pos.stores (
    store_id        INTEGER GENERATED BY DEFAULT AS IDENTITY,
    area_id         SMALLINT     NOT NULL,
    store_code      VARCHAR(20)  NOT NULL,
    store_name      VARCHAR(120) NOT NULL,
    store_type      VARCHAR(20)  NOT NULL,
    city            VARCHAR(80)  NOT NULL,
    latitude        NUMERIC(9,6),
    longitude       NUMERIC(9,6),
    opened_date     DATE         NOT NULL,
    closed_date     DATE,
    status          VARCHAR(20)  NOT NULL DEFAULT 'active',
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now()
);
COMMENT ON TABLE  pos.stores IS 'Physical stores. One row per store. Mutable: area reassignment, status, closure.';
COMMENT ON COLUMN pos.stores.area_id     IS 'Current area. Changes are captured downstream as SCD2 (dim_store).';
COMMENT ON COLUMN pos.stores.closed_date IS 'NULL while the store is trading.';

-- -----------------------------------------------------------------------------
-- Product hierarchy: product_categories -> products
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS pos.product_categories (
    category_id     SMALLINT GENERATED BY DEFAULT AS IDENTITY,
    category_name   VARCHAR(60)  NOT NULL,
    category_group  VARCHAR(20)  NOT NULL
);
COMMENT ON TABLE pos.product_categories IS 'Static reference: menu categories (e.g. Espresso, Frappe, Pastry). One row per category.';

CREATE TABLE IF NOT EXISTS pos.products (
    product_id      INTEGER GENERATED BY DEFAULT AS IDENTITY,
    category_id     SMALLINT     NOT NULL,
    sku             VARCHAR(30)  NOT NULL,
    product_name    VARCHAR(120) NOT NULL,
    size            VARCHAR(10),
    base_price      NUMERIC(12,2) NOT NULL,
    unit_cost       NUMERIC(12,2) NOT NULL,
    is_active       BOOLEAN      NOT NULL DEFAULT TRUE,
    launched_date   DATE         NOT NULL,
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now()
);
COMMENT ON TABLE  pos.products IS 'Sellable menu items (SKU level; each size is its own SKU). Mutable: price, cost, category, active flag.';
COMMENT ON COLUMN pos.products.size       IS 'NULL for items without a size (food, merchandise).';
COMMENT ON COLUMN pos.products.base_price IS 'Current list price. Price actually charged is stored on order_items.unit_price.';
COMMENT ON COLUMN pos.products.unit_cost  IS 'Current unit cost. Historical cost is recovered downstream from SCD2 history (dim_product).';

-- -----------------------------------------------------------------------------
-- Customers (loyalty members). Walk-in buyers are not customers.
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS pos.customers (
    customer_id     BIGINT GENERATED BY DEFAULT AS IDENTITY,
    full_name       VARCHAR(120) NOT NULL,
    email           VARCHAR(254),
    phone           VARCHAR(20),
    birth_date      DATE,
    gender          VARCHAR(20),
    city            VARCHAR(80),
    signup_date     DATE         NOT NULL,
    signup_store_id INTEGER,
    loyalty_tier    VARCHAR(20)  NOT NULL DEFAULT 'basic',
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now()
);
COMMENT ON TABLE  pos.customers IS 'Registered loyalty customers (100% synthetic PII). One row per customer. Mutable: profile, loyalty tier.';
COMMENT ON COLUMN pos.customers.signup_store_id IS 'Home store where the customer registered; NULL if signed up via app.';

-- -----------------------------------------------------------------------------
-- Promotions
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS pos.promotions (
    promotion_id     INTEGER GENERATED BY DEFAULT AS IDENTITY,
    promo_code       VARCHAR(30)  NOT NULL,
    promo_name       VARCHAR(120) NOT NULL,
    promo_type       VARCHAR(20)  NOT NULL,
    discount_value   NUMERIC(12,2) NOT NULL,
    min_order_amount NUMERIC(12,2) NOT NULL DEFAULT 0,
    start_date       DATE         NOT NULL,
    end_date         DATE         NOT NULL,
    updated_at       TIMESTAMPTZ  NOT NULL DEFAULT now()
);
COMMENT ON TABLE  pos.promotions IS 'Order-level promotional campaigns. One row per promotion.';
COMMENT ON COLUMN pos.promotions.discount_value IS 'percent: 0-100 (percentage off); fixed: PHP amount off; bundle: PHP amount off the bundle.';

-- -----------------------------------------------------------------------------
-- Transactions: orders -> order_items, orders -> payments
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS pos.orders (
    order_id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    order_number     VARCHAR(30)  NOT NULL,
    store_id         INTEGER      NOT NULL,
    customer_id      BIGINT,                      -- NULL = walk-in (anonymous) order
    promotion_id     INTEGER,                     -- NULL = no promotion applied
    order_ts         TIMESTAMPTZ  NOT NULL,
    order_channel    VARCHAR(20)  NOT NULL,
    order_status     VARCHAR(20)  NOT NULL DEFAULT 'completed',
    subtotal         NUMERIC(12,2) NOT NULL,
    discount_amount  NUMERIC(12,2) NOT NULL DEFAULT 0,
    tax_amount       NUMERIC(12,2) NOT NULL DEFAULT 0,
    total_amount     NUMERIC(12,2) NOT NULL,
    updated_at       TIMESTAMPTZ  NOT NULL DEFAULT now()
);
COMMENT ON TABLE  pos.orders IS 'POS order header. One row per order (ticket). Mutable: status (cancel/refund).';
COMMENT ON COLUMN pos.orders.subtotal        IS 'Sum of line_total before order-level discount.';
COMMENT ON COLUMN pos.orders.discount_amount IS 'Order-level (promotion) discount.';
COMMENT ON COLUMN pos.orders.total_amount    IS 'Amount due: subtotal - discount_amount + tax_amount. Cross-column/cross-table reconciliation is tested downstream (dbt), not enforced here.';

CREATE TABLE IF NOT EXISTS pos.order_items (
    order_item_id    BIGINT GENERATED BY DEFAULT AS IDENTITY,
    order_id         BIGINT       NOT NULL,
    product_id       INTEGER      NOT NULL,
    quantity         INTEGER      NOT NULL,
    unit_price       NUMERIC(12,2) NOT NULL,
    line_discount    NUMERIC(12,2) NOT NULL DEFAULT 0,
    line_total       NUMERIC(12,2) NOT NULL,
    updated_at       TIMESTAMPTZ  NOT NULL DEFAULT now()
);
COMMENT ON TABLE  pos.order_items IS 'Order lines. One row per product line on an order. The same product may appear on more than one line.';
COMMENT ON COLUMN pos.order_items.unit_price    IS 'Price charged at time of sale (may differ from current products.base_price).';
COMMENT ON COLUMN pos.order_items.line_discount IS 'Line-level discount (e.g. item promo), separate from order-level discount.';
COMMENT ON COLUMN pos.order_items.line_total    IS 'quantity * unit_price - line_discount.';

CREATE TABLE IF NOT EXISTS pos.payments (
    payment_id       BIGINT GENERATED BY DEFAULT AS IDENTITY,
    order_id         BIGINT       NOT NULL,
    payment_method   VARCHAR(20)  NOT NULL,
    amount           NUMERIC(12,2) NOT NULL,
    payment_status   VARCHAR(20)  NOT NULL DEFAULT 'paid',
    paid_at          TIMESTAMPTZ  NOT NULL,
    updated_at       TIMESTAMPTZ  NOT NULL DEFAULT now()
);
COMMENT ON TABLE  pos.payments IS 'Payment events. One row per tender or refund event; an order can have many (split tender, refunds).';
COMMENT ON COLUMN pos.payments.amount         IS 'Always positive. Direction comes from payment_status (refunded = money returned).';
COMMENT ON COLUMN pos.payments.payment_status IS 'paid = money received; failed = declined attempt; refunded = refund event.';
